apiVersion: v1
kind: persistentVolume
metadata:
  name: postgress-pv
  namespace: three-tier
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostpath:
     path: /data/postgres
  
  
