apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: three-tier
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
   
