FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

  RUN apt-get update &&
      apt-get install -y --no=install-recommends \
      supervisor
      rm -rf /var/lib/apt/lists/*

COPY       
  

  
